/UE_PROJECT
│── app.py                    # Streamlit Dashboard - Entry point to run the pipeline
│── config.py                 # Configuration file (API keys, settings)
│── modules
│   │── llm_generator.py      # Generates and confirms dialogue generated by LLM
│   │── audio_generator.py    # Uses ElevenLabs API to generate voice
│   │── sequence_editor.py    # Edits Unreal Engine sequence using Python API
│   │── lipsync_handler.py    # Handles lipsync using Metahuman SDK
│   │── video_renderer.py     # Renders final sequence in Unreal
│── utils                     # Utility functions
│   │── file_utils.py         # Handles file operations
│   │── unreal_utils.py       # Unreal-specific helper functions
│── generated    
